on: [push]

jobs:
  start-mongo:
    runs-on: ubuntu-latest
    name: job that starts mongo server 
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: start mongo 
        uses: supercharge/mongodb-github-action@latest

      - name: get time
        run: echo "The time was ${{steps.hello.outputs.time}}"
      

